backend:
  name: git-gateway

media_folder: static/images
public_folder: /images

collections:
  - name: pages
    label: Pages
    format: json
    files:
      - file: src/data/phrases.json
        label: Phrases
        name: phrases
        widget: list
        fields:
          - { label: Title, name: title, widget: string }
          - { label: ID, name: phraseId, widget: string }
