backend:
  name: test-repo

collections:
  - label: 'Phrases'
    name: 'phrases'
    folder: 'phrases'
    create: true
    files:
      - label: 'Phrase'
        name: 'phrase'
        format: 'json'
        file: 'scr/data/phrases.json'
        fields:
          - { label: ID, name: phraseId, widget: string }
          - { label: Title, name: title, widget: string }
