backend:
  name: git-gateway

media_folder: static/images
public_folder: /images
#G!nger007
collections:
  - name: pages
    label: Pages
    format: json
    files:
      - file: src/data/phrases.json
        label: Phrases
        name: phrases
        fields:
          - label: Phrase
            name: phrase
            widget: list
            fields:
              - { label: Title, name: title, widget: string }
              - { label: ID, name: phraseId, widget: string }
